version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    volumes:
      - ${APP_DATA_DIR}/data/config:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - ${UMBREL_ROOT}/data/storage/media:/media   # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
    environment:
      - PUID=1000         # uid
      - PGID=1000         # gid
      - PERMS=false       # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    restart: always
    network_mode: bridge
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整